# --- example config file --- 
# copy this file, rename to 'config.yaml'
# update this file with your actual paths/info
# make sure to add the your config.yaml to gitignore!

PATHS:
  BASE_PATH: "/path/to/directoryForSagemicFiles"
  PATH_TO_CA_PEM: "/path/to/rootCA"
  PATH_TO_CRT: "/path/to/clientcrt"
  PATH_TO_KEY: "/path/to/clientkey"

SETTINGS:
  # Change  if outside of San Diego
  LATITUDE: 32.7157
  LONGITUDE: -117.1611
  LOCAL_TZ: "America/Los_Angeles"

  # Default for audio device
  SAMPLERATE: 48000
  CONFIDENCE_THRESHOLD: 0.1
  BLOCK_DURATION: 3

  # for audio_device, enter exact name from arecord-l in brackets
  # audiomoth: 48kHz AudioMoth USB Microphone
  # inmp441: snd_rpi_googlevoicehat_soundcar
  AUDIO_DEVICE: "exact_name_from_arecord-l"
  AUDIO_DTYPE: "int16_or_int32"

  # 1 for RMS Filtering of Audio Chunks, 0 for Continuous Recording
  RMS_FILTER: 1

  # Trigger threshold multiplier (typically 1.05-2.0)
  # Multiply current ambient RMS by this value to set trigger threshold
  # Example: 1.1 = Trigger inference if sound is 10% louder than backgroud noise.  
  # Lower values = higher sensitivity, catches faint calls but more false triggers
  THRESH_MULTIPLIER: 1.1

  # Exponential Moving Average (EMA) smoothing factor for noise floor adaptation
  # Typically 0.01 - 0.5, controls how fast ambient noise floor adapts to env. changes
  # Example: 0.1 = New non-detection audio chunks contribute 10% to noise floor
  # Lower values = slow adaptation (good for stable environments)
  EMA_ALPHA: 0.1

MQTT:
  # Default Port for MQTTS
  PORT: 8883
  # Usage: NodeRed assumes the first slash parses the base_topic and device name.
  # If a slash is used in base_topic, make sure to adjust the parsing on NodeRed 
  BASE_TOPIC: "topic_name"
  DEVICE: "device_name"
  BROKER: "<ip>"
